name: Automatically publish to Modrinth and CurseForge
on:
  release:
    types: [published]
jobs:
  publish-to-curseforge:
    if: github.repository_owner == 'Fabulously-Optimized'
    runs-on: ubuntu-24.04
    environment: github-actions
    steps:
       - name: Download pack files
         uses: robinraju/release-downloader@v1.12
         id: download-files
         with:
           fileName: "*.zip"
           latest: true
           tarBall: false
           zipBall: false
           preRelease: true

       - name: Publish to CurseForge
         uses: Kir-Antipov/mc-publish@v3.3
         with:
           name: ${{ steps.download-files.outputs.tag_name }} for ${{ vars.MC_VERSION }}
           curseforge-id: 396246
           curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
           curseforge-files: '*.zip'
           loaders: fabric
           game-versions: ${{ vars.MC_VERSION }}
           
  publish-to-modrinth:
    runs-on: ubuntu-24.04
    environment: github-actions
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
         with:
           persist-credentials: false
       - name: Download packwiz
         uses: actions/download-artifact@v4
         with:
           name: "Linux 64-bit x86"
           github-token: ${{ secrets.GH_PAT }}
           repository: Madis0/packwiz
           run-id: 14577699585
       - name: Export to packwiz
         run: |
           chmod +x ./packwiz
           pushd Packwiz/${{ vars.MC_VERSION }}
           ../../packwiz modrinth export -o ../../Fabulously.Optimized-${{ github.ref_name }}.mrpack
           popd
       - name: Upload to Github
         uses: Shopify/upload-to-release@v2.0.0
         with:
           name: Fabulously.Optimized-${{ github.ref_name }}.mrpack
           path: Fabulously.Optimized-${{ github.ref_name }}.mrpack
           repo-token: ${{ secrets.GITHUB_TOKEN }}
